[package]
name = "test_rust_proj"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.3", features = ["default_fonts", "glow"] }
egui_extras = { version = "0.33.3", features = ["all_loaders"] }
open = "5.0"